Allow unused labels in the generated ling_main.c
Running `make railing` from a clean working copy in recent master I
got the following a warning (treated as error) for `l_apply_entry`
label being unused.  It is supposed to be used by `l_hibernate` that
is not included in `ling_main.c` hence the warning/error.

In my understanding the included opcodes are determined at build time
so this is a perfectly valid scenario.

Below the full error:
```
scripts/main_gen scripts/ling_main_c.et scripts/hot_cold_iops
gcc -Wall -Werror -std=gnu99 -O3 -fexcess-precision=standard -frounding-math -mfpmath=sse
 -msse2 -Wno-nonnull -Wno-strict-aliasing -fno-stack-protector -U_FORTIFY_SOURCE -fno-omi
 t-frame-pointer -flto -D_ISOC99_SOURCE -D_GNU_SOURCE -iquote lib -isystem lib/misc/includ
 e -isystem lib/pcre -isystem lib -iquote include -iquote arch/x86/include -iquote bignum
 -iquote lib/lwip/src/include -iquote lib/lwip/src/include/ipv4 -iquote lib/lwip/src/inclu
 de/ipv6 -iquote lib/lwip/ling -D__XEN_INTERFACE_VERSION__=0x00030205 -DLING_VER=0.3.1 -DL
 ING_DEBUG -DDEBUG_UNUSED_MEM -DTRACE_HARNESS -fno-reorder-blocks -o ling_main.o -c ling_m
 ain.c
 ling_main.c: In function ‘proc_main’:
 ling_main.c:27241:1: error: label ‘l_apply_entry’ defined but not used [-Werror=unused-la
 bel]
  l_apply_entry:
   ^
   cc1: all warnings being treated as errors
   make[1]: *** [ling_main.o] Error 1
   make[1]: Leaving directory `/home/vagrant/dev/ling/ling/core'
   make: *** [core] Error 2
```